---

- name: Configure User
  ansible.builtin.include_tasks:
    file: user.yml

- name: Check if /boot/firmware directory exists
  ansible.builtin.stat:
    path: /boot/firmware
  register: boot_firmware_dir

- name: Configure OS
  ansible.builtin.include_tasks:
    file: os.yml

- name: Configure Hardware
  ansible.builtin.include_tasks:
    file: hardware.yml
  when: ansible_facts.architecture == 'aarch64'
