{
 "title": "DFLD",
 "time": { "from": "2025-03-03T05:39:45.611Z", "to": "2025-03-03T08:46:30.697Z" },
 "panels": [
  {
   "title": "DFLD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "DNMS dB A avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dnms_serial",
     "query": "SELECT mean(\"dB_A_avg\") FROM \"dnms_serial\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dB_A_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DFLD dB A avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dfld_serial",
     "select": [
      [
       { "params": [ "dB_A_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DNMS i2c dB A avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dnms_i2c",
     "select": [
      [
       { "params": [ "dB_A_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gesamtzahl Überflüge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "events",
     "query": "SELECT count() FROM \"events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "callsign" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Überflüge pro Stunde",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 9 },
   "targets": [
    {
     "alias": "NW",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "icao_id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "dist::field", "operator": "<=", "value": "1200" }
     ]
    },
    {
     "alias": "Central",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "icao_id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "dist::field", "operator": ">", "value": "1200" }
     ]
    }
   ]
  },
  {
   "title": "Überflugsliste",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 9 },
   "targets": [
    {
     "alias": "Letzte Überflüge",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "limit": "10",
     "measurement": "events",
     "query": "SELECT \"callsign\" as Callsign, \"dist\" as Distance, \"icao_id\" as ICAO FROM \"events\" WHERE $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "callsign" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Minimaler Überflugabstand",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "alias": "Minimal Distance / m",
     "measurement": "events",
     "query": "SELECT \"dist\" FROM \"events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "dist" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "Luftdruck",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lufttemperatur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "relative Luftfeuchtigkeit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}