---

- name: Read infrastructure env file
  ansible.builtin.set_fact:
    compose_env: "{{ dict(lookup('template', playbook_dir ~ '/templates/container/compose.env.j2').split() | map('split', '=', 1)) }}"

- name: Read infrastructure yml compose file
  ansible.builtin.set_fact:
    compose_yaml: "{{ lookup('template', playbook_dir ~ '/templates/container/ingress-compose.yml.j2') | from_yaml }}"

- name: Deploy stack ingress, if not exists
  ansible.builtin.uri:
    url: "https://localhost:9443/api/stacks/create/standalone/string?endpointId={{ portainer_endpoint_data.Id }}"
    method: POST
    body_format: json
    validate_certs: false
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ portainer_auth.json.jwt }}"
    body: >-
     { "name": "ingress",
       "env": {{ compose_env | dict2items(key_name="name", value_name="value") | to_json }},
       "stackFileContent": {{ compose_yaml | to_nice_yaml | to_json }} }
    timeout: 600
    status_code: 200
  when: "'ingress' not in portainer_stacks.json|map(attribute='Name')"
