---

- name: Create homepage config folder
  ansible.builtin.file:
    path: "{{ dfld_dir }}/homepage/{{ homepage_folder }}"
    owner: "{{ dfld_user_info.uid }}"
    group: "{{ dfld_user_info.group }}"
    state: directory
    mode: '0755'
  loop:
    - config
    - icons
  loop_control:
    loop_var: homepage_folder

- name: Create homepage config file
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/homepage/{{ homepage_config }}.j2"
    dest: "{{ dfld_dir }}/homepage/config/{{ homepage_config }}"
    owner: "{{ dfld_user_info.uid }}"
    group: "{{ dfld_user_info.group }}"
    mode: '0644'
  loop:
    - bookmarks.yaml
    - docker.yaml
    - services.yaml
    - settings.yaml
    - widgets.yaml
  loop_control:
    loop_var: homepage_config

- name: Create homepage icons
  ansible.builtin.copy:
    src: "{{ homepage_icon }}"
    dest: "{{ dfld_dir }}/homepage/icons"
    owner: "{{ dfld_user_info.uid }}"
    group: "{{ dfld_user_info.group }}"
    mode: '0644'
  with_fileglob:
    - "{{ playbook_dir }}/files/homepage/*.svg"
    - "{{ playbook_dir }}/files/homepage/*.png"
  loop_control:
    loop_var: homepage_icon

- name: Create HOMEPAGE_ALLOWED_HOSTS list
  ansible.builtin.set_fact:
    homepage_allowed_hosts: "{{ (homepage_allowed_hosts_list + user_allowed_homepage_hosts) | unique | reject('equalto', '') | join(',') }}"
  vars:
    homepage_allowed_hosts_list:
      - "{{ ansible_default_ipv4.address }}"
      - "{{ ansible_fqdn }}"
      - "{{ ansible_hostname }}"
      - "{{ 'dfld-' + (dfld_region if dfld_region | length > 0 else '000') + '-' + (dfld_station if dfld_station | length > 0 else '000') }}"
