---

- name: Copy telegraf config
  ansible.builtin.copy:
    src: "telegraf.conf"
    dest: "{{ dfld_dir }}/telegraf.conf"
    mode: '0644'

- name: Read infrastructure env file
  ansible.builtin.set_fact:
    compose_env: "{{ dict(lookup('template', 'compose.env.j2').split() | map('split', '=')) }}"

- name: Read infrastructure yml compose file
  ansible.builtin.set_fact:
    compose_yaml: "{{ lookup('template', 'infrastructure-compose.yml.j2') | from_yaml }}"

- name: Remove adsb software, if no hardware found
  ansible.builtin.set_fact:
    compose_yaml: "{{ compose_yaml | ansible.utils.remove_keys(target=['ultrafeeder']) }}"
  when: hw_conf["ADSB_AVAILABLE"] == 0

- name: Deploy stack infrastructure, if not exists
  ansible.builtin.uri:
    url: "https://localhost:9443/api/stacks/create/standalone/string?endpointId={{ portainer_endpoint_data.Id }}"
    method: POST
    body_format: json
    validate_certs: false
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ portainer_auth.json.jwt }}"
    body: >-
      { "name": "infrastructure",
         "env": {{ compose_env | dict2items(key_name="name", value_name="value") | to_json }},
         "stackFileContent": {{ compose_yaml | to_nice_yaml | to_json }} }
    timeout: 300
    status_code: 200
  when: "'infrastructure' not in portainer_stacks.json|map(attribute='Name')"
