---

- name: Create mqtt config folder
  ansible.builtin.file:
    path: "{{ dfld_dir }}/mqtt/config"
    owner: "{{ dfld_user_info.uid }}"
    group: "{{ dfld_user_info.group }}"
    state: directory
    mode: '0755'

- name: Create mqtt config file
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/mqtt/mosquitto.conf.j2"
    dest: "{{ dfld_dir }}/mqtt/config/mosquitto.conf"
    owner: "{{ dfld_user_info.uid }}"
    group: "{{ dfld_user_info.group }}"
    mode: '0644'
