{
 "title": "DFLD",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "DFLD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "DNMS dB A avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spl",
     "query": "SELECT mean(\"dB_A_avg\") FROM \"spl\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dB_A_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gesamtzahl Überflüge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(dist_xy) FROM event_raw WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Überflugsliste",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 9 },
   "targets": [
    {
     "query": "SELECT dist_xy, dist_z, descr, flight, hex, r, t FROM event_raw WHERE $timeFilter ORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "Luftdruck",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lufttemperatur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "relative Luftfeuchtigkeit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spectrogramm",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "dB Z",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thirds",
     "query": "SELECT mean(\"LZeq20\"), mean(\"LZeq25\"), mean(\"LZeq31.5\"), mean(\"LZeq40\"), mean(\"LZeq50\"), mean(\"LZeq63\"), mean(\"LZeq80\"), mean(\"LZeq100\"), mean(\"LZeq125\"), mean(\"LZeq160\"), mean(\"LZeq200\"), mean(\"LZeq250\"), mean(\"LZeq315\"), mean(\"LZeq400\"), mean(\"LZeq500\"), mean(\"LZeq630\"), mean(\"LZeq800\"), mean(\"LZeq1000\"), mean(\"LZeq1250\"), mean(\"LZeq1600\"), mean(\"LZeq2000\"), mean(\"LZeq2500\"), mean(\"LZeq3150\"), mean(\"LZeq4000\"), mean(\"LZeq5000\"), mean(\"LZeq6300\"), mean(\"LZeq8000\"), mean(\"LZeq10000\"), mean(\"LZeq12500\"), mean(\"LZeq16000\"), mean(\"LZeq20000\") FROM \"thirds\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "LAeq20" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lateraler Überflugabstand (dist_xy)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "SELECT dist_xy FROM event_raw WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Vertikaler Überflugabstand (dist_z, Aircraft − Station)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "SELECT dist_z FROM event_raw WHERE $timeFilter"
    }
   ]
  }
 ]
}